version: '3.2'

services:
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
